name: Hybrid IPTV Cloud Update

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Загрузка репозитория
      uses: actions/checkout@v4

    - name: Настройка Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Запуск Супербота
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python smart_bot.py
